#The hostnames of the computers in the cluster. Use hostnames and not 
#IP addresses as this has Windows security implications.
computers:
  - Jupiter
  - Mars
  - Polaris
  #- Pluto

#The username to use for creating credentials. By default the local
#user is the one that is used.
username: $env:USERNAME

#The location where the encrypted credential file will be stored
#This location will be relative to the scripts folder
credentialFile: ".\\credential.xml"