computers:
  - Jupiter
  - Mars
  - Polaris
reposFolder: "\\\\Polaris\\GitRepos"
gitProject: "C:\\Users\\Public\\Projects\\TDSynchro"
username: $env:USERNAME
credentialFile: "$gitProject\\Scripts\\credential.xml"